# Generated by Django 2.2.4 on 2019-08-20 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Row',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_val', models.CharField(max_length=3)),
                ('i_val', models.CharField(max_length=3)),
                ('n_val', models.CharField(max_length=3)),
                ('g_val', models.CharField(max_length=3)),
                ('o_val', models.CharField(max_length=3)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='play.Card')),
            ],
        ),
    ]
