# Generated by Django 2.2.4 on 2019-08-25 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ball',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_value', models.IntegerField()),
                ('updated_at', models.DateTimeField(null=True)),
                ('is_played', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MatchSmiley',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('one_value', models.CharField(max_length=3)),
                ('two_value', models.CharField(max_length=3)),
                ('three_value', models.CharField(max_length=3)),
                ('four_value', models.CharField(max_length=3)),
                ('five_value', models.CharField(max_length=3)),
                ('six_value', models.CharField(max_length=3)),
                ('seven_value', models.CharField(max_length=3)),
                ('eight_value', models.CharField(max_length=3)),
                ('nine_value', models.CharField(max_length=3)),
                ('ten_value', models.CharField(max_length=3)),
                ('eleven_value', models.CharField(max_length=3)),
                ('twelve_value', models.CharField(max_length=3)),
                ('thirteen_value', models.CharField(max_length=3)),
                ('fourteen_value', models.CharField(max_length=3)),
                ('needed_to_win', models.IntegerField()),
                ('left', models.IntegerField()),
            ],
        ),
    ]
